#############################################################################
# Makefile for building: TrainTable
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 1. ??? 20:39:59 2013
# Project:  TrainTable.pro
# Template: app
# Command: d:\symbian\qtsdk112\symbian\sdks\symbian3qt473\bin\qmake.exe -spec ..\..\..\QtSDK112\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf TrainTable.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = d:\symbian\qtsdk112\symbian\sdks\symbian3qt473\bin\qmake.exe
DEL_FILE          = del 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQ_COMPONENTS_SYMBIAN -DHAVE_MOBILITY -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/include/QtCore"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/include/QtNetwork"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/include/QtGui"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/include/QtDeclarative"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/include"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/include/QtLocation"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/mkspecs/common/symbian"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/stdapis"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/stdapis/sys"  -I"D:/Symbian/QtSDK/workspace/TrainTable/qmlapplicationviewer"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/mw"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/mw"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/loc"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/mw/loc"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/loc/sc"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/mw/loc/sc"  -I"D:/QtMobility"  -I"D:/QtLocation"  -I"D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/include/stdapis/stlportv5"  -I"D:/Symbian/QtSDK/workspace/TrainTable/moc"  -I"D:/Symbian/QtSDK/workspace/TrainTable"  -I"D:/Symbian/QtSDK/workspace/TrainTable/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "D:/Symbian/QtSDK/workspace/TrainTable/TrainTable.pro"  -spec ..\..\..\QtSDK112\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: D:/Symbian/QtSDK/workspace/TrainTable/TrainTable.pro
	$(QMAKE) "D:/Symbian/QtSDK/workspace/TrainTable/TrainTable.pro"  -spec ..\..\..\QtSDK112\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc: 
	$(QMAKE) "D:/Symbian/QtSDK/workspace/TrainTable/TrainTable.pro"  -spec ..\..\..\QtSDK112\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb
release: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c armv5_urel -c armv6_urel
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c armv5_urel -c armv6_urel
freeze-release: bld.inf
	$(SBS) freeze -c armv5_urel -c armv6_urel

debug-winscw: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-rvct2.2: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v5.udeb.rvct2_2
clean-debug-armv5-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.rvct2_2
freeze-debug-armv5-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v5.udeb.rvct2_2
release-armv5-rvct2.2: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v5.urel.rvct2_2
clean-release-armv5-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.rvct2_2
freeze-release-armv5-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v5.urel.rvct2_2
debug-armv5-gcce4.4.1: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-rvct2.2: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v6.udeb.rvct2_2
clean-debug-armv6-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.rvct2_2
freeze-debug-armv6-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v6.udeb.rvct2_2
release-armv6-rvct2.2: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v6.urel.rvct2_2
clean-release-armv6-rvct2.2: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.rvct2_2
freeze-release-armv6-rvct2.2: bld.inf
	$(SBS) freeze -c arm.v6.urel.rvct2_2
debug-armv6-gcce4.4.1: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel

freeze: freeze-release

check: first

run:
	call D:/Symbian/QtSDK112/Symbian/SDKs/Symbian3Qt473/epoc32/release/winscw/udeb/TrainTable.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis TrainTable.sis TrainTable.exe $(QT_RUN_OPTIONS)

TrainTable_template.pkg: D:/Symbian/QtSDK/workspace/TrainTable/TrainTable.pro
	$(MAKE) -f $(MAKEFILE) qmake

TrainTable_installer.pkg: D:/Symbian/QtSDK/workspace/TrainTable/TrainTable.pro
	$(MAKE) -f $(MAKEFILE) qmake

TrainTable_stub.pkg: D:/Symbian/QtSDK/workspace/TrainTable/TrainTable.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: TrainTable_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	createpackage -g $(QT_SIS_OPTIONS) TrainTable_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: TrainTable_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	createpackage -g $(QT_SIS_OPTIONS) -o TrainTable_template.pkg $(QT_SIS_TARGET)

TrainTable.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: TrainTable_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: TrainTable_installer.pkg
	createpackage $(QT_SIS_OPTIONS) TrainTable_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: TrainTable_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: TrainTable_installer.pkg
	createpackage $(QT_SIS_OPTIONS) -o TrainTable_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: TrainTable_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	createpackage -s $(QT_SIS_OPTIONS) TrainTable_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call TrainTable.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_application.cpp moc\moc_stationgetter.cpp moc\moc_timetable.cpp moc\moc_map.cpp moc\moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_application.cpp moc\moc_stationgetter.cpp moc\moc_timetable.cpp moc\moc_map.cpp moc\moc_qmlapplicationviewer.cpp
moc\moc_application.cpp: stationgetter.h \
		timetable.h \
		map.h \
		const.h \
		application.h
	D:\Symbian\QtSDK112\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\TrainTable\application.h -o d:\Symbian\QtSDK\workspace\TrainTable\moc\moc_application.cpp

moc\moc_stationgetter.cpp: stationgetter.h
	D:\Symbian\QtSDK112\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\TrainTable\stationgetter.h -o d:\Symbian\QtSDK\workspace\TrainTable\moc\moc_stationgetter.cpp

moc\moc_timetable.cpp: timetable.h
	D:\Symbian\QtSDK112\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\TrainTable\timetable.h -o d:\Symbian\QtSDK\workspace\TrainTable\moc\moc_timetable.cpp

moc\moc_map.cpp: const.h \
		map.h
	D:\Symbian\QtSDK112\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\TrainTable\map.h -o d:\Symbian\QtSDK\workspace\TrainTable\moc\moc_map.cpp

moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	D:\Symbian\QtSDK112\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\Symbian\QtSDK\workspace\TrainTable\qmlapplicationviewer\qmlapplicationviewer.h -o d:\Symbian\QtSDK\workspace\TrainTable\moc\moc_qmlapplicationviewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

dodistclean:
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_template.pkg" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_template.pkg"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_stub.pkg" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_stub.pkg"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_installer.pkg" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_installer.pkg"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\Makefile" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\Makefile"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_exe.mmp" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_exe.mmp"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_reg.rss" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable_reg.rss"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.rss" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.rss"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\TrainTable.loc"
	-@ if EXIST "d:\Symbian\QtSDK\workspace\TrainTable\bld.inf" $(DEL_FILE)  "d:\Symbian\QtSDK\workspace\TrainTable\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c armv5_udeb -c armv6_udeb -c armv5_urel -c armv6_urel


